# Generated by Django 5.1.6 on 2025-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_videobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopMainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_text', models.CharField(max_length=100)),
                ('image_left', models.ImageField(upload_to='banners/')),
                ('image_right', models.ImageField(upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
