# Generated by Django 5.1.6 on 2025-12-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmainbanner',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
