# Generated by Django 5.1.6 on 2025-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shopmainbanner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmainbanner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
