# Generated by Django 5.1.6 on 2025-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_shopmainbanner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='home_categories/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopmainbanner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopmainbanner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
