# Generated by Django 5.1.6 on 2025-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homecategory_alter_shopmainbanner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategory',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
