# Generated by Django 5.1.6 on 2025-03-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mostsold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='newarrived',
            field=models.BooleanField(default=False),
        ),
    ]
