# Generated by Django 5.1.6 on 2025-03-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_created_at_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
