# Generated by Django 5.1.6 on 2025-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sofas', 'Sofas'), ('Beds', 'Beds'), ('Tables', 'Tables'), ('Book Shelf', 'Book Shelf'), ('Cabinet', 'Cabinet'), ('Dining', 'Dining'), ('Bar', 'Bar'), ('Pooja', 'Pooja'), ('TV Units', 'TV Units'), ('Wardrobe', 'Wardrobe'), ('Wall Panels', 'Wall Panels'), ('Paintings', 'Paintings')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
