# Generated by Django 5.1.6 on 2025-04-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[('collection1', 'Collection_1'), ('collection2', 'Collection_2'), ('collection3', 'Collection_3'), ('collection4', 'Collection_4')], max_length=50, null=True),
        ),
    ]
