# Generated by Django 5.1.6 on 2025-03-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_in_stock_product_newin_product_topselling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewArrival', models.BooleanField(default=False)),
                ('MostSold', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtship', to='product.product')),
            ],
        ),
    ]
