# Generated by Django 5.1.6 on 2025-07-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_collection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
    ]
