# Generated by Django 5.1.6 on 2025-03-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rtship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtship',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='RTShip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.rtship'),
        ),
    ]
