# Generated by Django 5.1.6 on 2025-07-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
    ]
