# Generated by Django 5.1.6 on 2025-12-13 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_trending', models.BooleanField(default=False, help_text='Check if this is a trending item')),
                ('image', models.ImageField(upload_to='shop_collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_id', models.CharField(blank=True, help_text='e.g., collection1', max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='collectionlist',
            name='collectionlist',
        ),
        migrations.RemoveField(
            model_name='collectionlist',
            name='products',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='finishes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.shopcollection'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionList',
        ),
    ]
