# Generated by Django 5.1.6 on 2025-03-06 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_rtship_product_product_rtship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='RTShip',
        ),
        migrations.AddField(
            model_name='rtship',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtship', to='product.product'),
        ),
    ]
