# Generated by Django 5.1.6 on 2025-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_shopcollection_remove_collectionlist_collectionlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='finishes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
