# Generated by Django 5.1.6 on 2025-03-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_rtship_rtship_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtship',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rtship', to='product.product'),
            preserve_default=False,
        ),
    ]
