# Generated by Django 5.1.6 on 2025-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_rtship_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('products', models.ManyToManyField(blank=True, related_name='rooms', to='product.product')),
            ],
        ),
    ]
